# Generated by Django 5.2 on 2025-05-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.CharField(
                blank=True,
                default="Автор не указан",
                help_text="Введите свое имя (никнейм)",
                max_length=50,
                null=True,
                verbose_name="Автор поста",
            ),
        ),
    ]
