# Generated by Django 5.2 on 2025-05-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title", "content", "created_at", "counter"],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
    ]
