# Generated by Django 5.2.1 on 2025-06-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blog_owner_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title", "content", "created_at", "counter"],
                "permissions": [
                    ("can_add_post", "Can add post"),
                    ("can_change_post", "Can change post"),
                    ("can_delete_post", "Can delete post"),
                ],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
    ]
