# Generated by Django 5.2.1 on 2025-06-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title", "content", "created_at", "counter"],
                "permissions": [("can_change_post", "Can change post"), ("can_delete_post", "Can delete post")],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
    ]
