# Generated by Django 5.2 on 2025-05-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name_plural": "контакты"},
        ),
    ]
