# Generated by Django 5.2 on 2025-05-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0, help_text="Укажите количество просмотров", verbose_name="Счетчик просмотров"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(help_text="Введите название сорта", max_length=150, verbose_name="Наименование"),
        ),
    ]
