# Generated by Django 5.2 on 2025-05-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_views_counter_alter_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="views_counter",
        ),
    ]
