# Generated by Django 5.2 on 2025-05-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("Комнатные горшечные растения", "Комнатные горшечные растения"),
                    ("Фуксии", "Фуксии"),
                    ("Узамбарские фиалки (сенполии)", "Узамбарские фиалки (сенполии)"),
                    ("Пеларгонии", "Пеларгонии"),
                    ("Суккуленты", "Суккуленты"),
                ],
                default="Комнатные горшечные растения",
                max_length=100,
                verbose_name="Наименование",
            ),
        ),
    ]
