# Generated by Django 5.2 on 2025-05-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="Введите описание категории", null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("Комнатные горшечные растения", "Комнатные горшечные растения"),
                    ("Фуксии", "Фуксии"),
                    ("Узамбарские фиалки (сенполии)", "Узамбарские фиалки (сенполии)"),
                    ("Пеларгонии", "Пеларгонии"),
                    ("Суккуленты", "Суккуленты"),
                ],
                default="Комнатные горшечные растения",
                help_text="Выберите название категории",
                max_length=100,
                verbose_name="Наименование",
            ),
        ),
    ]
