# Generated by Django 5.2.1 on 2025-06-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_category_description_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("published", "Опубликовано"), ("archived", "В архиве")],
                default="draft",
                max_length=20,
            ),
        ),
    ]
