# Generated by Django 5.2.1 on 2025-06-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_product_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price"],
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("can_delete_product", "Can delete product"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
