# Generated by Django 5.2.1 on 2025-06-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_alter_product_category_alter_product_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="default_temp", unique=True),
            preserve_default=False,
        ),
    ]
